name: promina_task
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dio: ^5.1.1
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.7.0
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^1.3.0
  pretty_dio_logger: ^1.3.1
  blurrycontainer: ^1.0.2
  blur: ^3.1.0
  flutter_form_builder: ^7.8.0
  form_builder_validators: ^8.5.0
  image_picker: ^0.8.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/



